USER_ID from session
margarita-ignatieva/jv_internet_shop pull request #9
Opened 2020-09-15 14:55 UTC by margarita-ignatieva

2020-09-15 18:49 UTC, vladislavshvets approved these changes
Everything is fine, but I have not found a LoginController that can be used to shorten the code, where is he?

2020-09-15 19:00 UTC, margarita-ignatieva commented
> Everything is fine, but I have not found a LoginController that can be used to shorten the code, where is he?

Was in a previous HW

2020-09-16 05:09 UTC, KseniiaMakarova reviewed
you have closed this PR
![image](https://user-images.githubusercontent.com/59459757/93294671-dfad1f80-f7f3-11ea-8a36-e886283f44e3.png)
you need to reopen it

2020-09-16 07:04 UTC, KseniiaMakarova requested changes

2020-09-16 07:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/cart/GetAllProductsFromCartController.java
> +        List<Product> addedProducts = shoppingCartService.getByUserId(userId).getProducts();
do you need to set attribute?

2020-09-16 07:15 UTC, margarita-ignatieva commented on src/main/java/com/internet/shop/controllers/cart/GetAllProductsFromCartController.java
> +        List<Product> addedProducts = shoppingCartService.getByUserId(userId).getProducts();
yes, missed it

2020-09-16 07:17 UTC, KseniiaMakarova approved these changes

2020-09-16 11:21 UTC, merged